### ISSUE TITLE
帮忙上传打包好的ipa

### ISSUE THREAD

**Issue by taoxul2006** [ssyzh/weworktweak#4]
帮忙上传打包好的ipa，可以用 impactor工具安装

**Comment by ssyzh** [comment]
可以将.app文件拖入iTunes ，将会自动打包成无签名的ipa，iTunes - 程序 - wework ，右键进入文件夹可以得到ipa文件。我目前无法安装Cydia Impactor，无法确认这种方式打包的ipa是否可以使用。如需要可以留下邮箱，我把这种方式打包出来的ipa发送给你。
