### ISSUE TITLE
项目里其他资源干什么用的？

### ISSUE THREAD

**Issue by youngzhu** [ssyzh/weworktweak#6]
看完README，好像一个教程，但跟其他资源有啥关系呢？会用到吗？

**Comment by ssyzh** [comment]
README是安装我写的theos文件的教程，其他没涉及的工具是制作theos文件的工具。

**Comment by ssyzh** [comment]
如果你需要🇭🇰教程，我可以发你一些，但是你首先需要一个越狱手机。
