### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Cui-y** [ssyzh/weworktweak#9]
请问重签名证书和配置文件怎么搞到？？

**Comment by Cui-y** [comment]
刚google了一下，貌似需要开发者账号， @ssyzh 可否放一个已经重签名好的ipa文件出来呢

**Comment by ssyzh** [comment]
开发者账号是公司的，无法提供打包后的ipa。不过我可以提供一个.app包，然后你可以使用自己的apple id 每7天自己重新签名。
